### ISSUE TITLE
TSDoc Comment Documentation

### ISSUE THREAD

**Issue by RealShadowNova** [RealShadowNova/centrum-framework#2]
For the framework there is a need for some well done documentation. It shouldn't be so hard to figure what class, method, or property does what.

Here is a list of classes that need proper documentation, make sure to document only the classes and their *public* children methods and properies. Remember, I'm not asking for JSDoc comments, I'm asking for TSDoc comments. So, your pretty much writing descriptions nothing much else. If you have questions, please comment your questions here or ask in the Discord Server.

- [x] [`CentrumClient`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/structures/CentrumClient.ts)
- [x] [`Command`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/structures/Command.ts)
- [x] [`BaseManager`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/structures/managers/BaseManager.ts)
- [x] [`CommandManager`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/structures/managers/CommandManager.ts)
- [x] [`DatabaseManager`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/structures/managers/DatabaseManager.ts)
- [x] [`PermissionLevelManager`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/structures/managers/PermissionLevelManager.ts)
- [x] [`DirRegistry`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/utils/DirRegistry.ts)
- [x] [`MessageHandler`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/utils/MessageHandler.ts)
- [x] [`Injector`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/injectors/Injector.ts)
- [x] [`InjectorManager`](https://github.com/RealShadowNova/centrum-framework/blob/master/src/lib/injectors/InjectorManager.ts)
